import './globals.css'
import Header from '@/components/Header'


export const metadata = {
  title: 'Food Search Site',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header/>
        {children}</body>
    </html>
  )
}
